version: '3'

services:
   node:
      build: .
#      image:
      ports:
         - ${PORT}:${PORT}
#      env_file:
#         - .env
      depends_on:
         - postgres
      environment:
         - PORT=${PORT}
   postgres:
      build: ./database/
#      image:
      environment:
         - POSTGRES_USERNAME=${POSTGRES_USERNAME}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
#      env_file:
#         - .env
      ports:
         - ${POSTGRES_PORT}:${POSTGRES_PORT}
#      volumes:
#

