version: '3'

services:
   node:
      build: .
      image: anastasiyazazerskaya/rs-nodejs
      ports:
         - ${PORT}:${PORT}
      restart: on-failure
      env_file:
         - .env
      depends_on:
         - postgres
      environment:
         - PORT=${PORT}
      volumes:
         - ./src:/app/rs-node-app/src
         - ./error.log:/app/rs-node-app/error.log
         - ./info.log:/app/rs-node-app/info.log
      networks:
         - my-net1
   postgres:
      build: ./database/
      image: anastasiyazazerskaya/rs-postgres
      environment:
         - POSTGRES_USERNAME=${POSTGRES_USERNAME}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=${POSTGRES_DB}
      env_file:
         - .env
      ports:
         - ${POSTGRES_PORT}:${POSTGRES_PORT}
      volumes:
         - ./database/data:/var/lib/postgresql/data
      networks:
         - my-net1

networks:
   my-net1:



